problem_two:
  lane_three:
    init_speed: 1.0
    lookahead: 0.5 #0.3
  lane_two:
    init_speed: 0.5
    lookahead: 0.5 #0.3
    
problem_three:
  roundabout:
    init_speed: 1.0
    lookahead: 0.35 
